# Generated by Django 4.1.5 on 2023-02-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('course', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('Frontend', 'Frontend')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='img/')),
                ('course', models.CharField(max_length=150)),
                ('mentor', models.CharField(choices=[('Madina', 'Madina'), ('Sherzod', 'Sherzod'), ('Sunnat', 'Sunnat'), ('Shahnoza', 'Shahnoza')], max_length=50)),
                ('raiting', models.IntegerField(max_length=10)),
                ('voices', models.CharField(max_length=50)),
                ('about_course', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='img/')),
                ('name', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=35)),
            ],
        ),
    ]
